### ISSUE TITLE
Get error "Cannot read property 'tap' of undefined"

### ISSUE THREAD

**Issue by gwynjudd** [jouni-kantola/razor-partial-views-webpack-plugin#69]
Hello,

I'm pretty new to using webpack and a lot of this stuff here, so please bear with me if I did something dumb.

I used create-react-app (with eject) to make an app, and then according to the guide, I added the plugin

```
        new RazorPartialViewsWebpackPlugin({
          rules: [{
            // view for default chunk
            name: "main",
            template: {
              // Razor directive
              header: "@inherits System.Web.Mvc.WebViewPage"
            }
          }]
        })
```

If I run `npm run build`, this output:

```
> my-app@0.1.0 build C:\Users\gjudd\Documents\Develop\temp\my-app
> node scripts/build.js

Creating an optimized production build...
Failed to compile.

Cannot read property 'tap' of undefined
```

And if I run `npm run start`, this:

```
Starting the development server...

C:\Users\gjudd\Documents\Develop\temp\my-app\scripts\start.js:11
  throw err;
  ^

TypeError: Cannot read property 'assets' of undefined
    at Compilation.createModuleAssets (C:\Users\gjudd\Documents\Develop\temp\my-app\node_modules\webpack\lib\Compilation.js:4481:25)
    at C:\Users\gjudd\Documents\Develop\temp\my-app\node_modules\webpack\lib\Compilation.js:3051:13
    at C:\Users\gjudd\Documents\Develop\temp\my-app\node_modules\webpack\lib\Compilation.js:3276:6
    at Object.eachLimit (C:\Users\gjudd\Documents\Develop\temp\my-app\node_modules\neo-async\async.js:3461:14)
    at runIteration (C:\Users\gjudd\Documents\Develop\temp\my-app\node_modules\webpack\lib\Compilation.js:3205:13)
    at Compilation._runCodeGenerationJobs (C:\Users\gjudd\Documents\Develop\temp\my-app\node_modules\webpack\lib\Compilation.js:3280:3)
    at C:\Users\gjudd\Documents\Develop\temp\my-app\node_modules\webpack\lib\Compilation.js:3036:12
    at C:\Users\gjudd\Documents\Develop\temp\my-app\node_modules\webpack\lib\Compilation.js:3276:6
    at C:\Users\gjudd\Documents\Develop\temp\my-app\node_modules\neo-async\async.js:2818:7
    at done (C:\Users\gjudd\Documents\Develop\temp\my-app\node_modules\neo-async\async.js:3522:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-app@0.1.0 start: `node scripts/start.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-app@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\gjudd\AppData\Roaming\npm-cache\_logs\2022-03-15T21_20_31_322Z-debug.log
```

Any suggestions for how to proceed?

thanks, Gwyn

**Comment by jouni-kantola** [comment]
Hi @gwynjudd!

Thanks for reaching out.

If possible, could you please upload a repro (without .git or node_modules folder)? If you can't, could you share your `package.json` and `webpack.config`?

**Comment by jouni-kantola** [comment]
I'll close this issue, as the problem most likely is a webpack configuration error rather than a bug in the plugin.

**Comment by gwynjudd** [comment]
@jouni-kantola thanks yes that seems to have been the problem. Once I moved it to the correct location, all was working as expected
